### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shi-an** [mimocvb/LiteLoaderQQNT-MessageEdit#18]
右键图片的右键菜单 会出现编辑消息内容 
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/06a34012-71ae-45db-b507-c4ab6cf3c1d5)
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/c3fa3642-1426-4f61-bafe-c8a33e2968ec)
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/4dceb8cd-4578-4ff3-be46-820f01dc39fa)

**Comment by mimocvb** [comment]
尝试使用最新1.0.4试试，昨天有优化过这个情况~

**Comment by shi-an** [comment]
1.0.4问题依旧

**Comment by mimocvb** [comment]
<img width="281" alt="1" src="https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/46435775/6cbf71b1-d825-4a2e-b1e9-b1b732b8076a">
<img width="165" alt="2" src="https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/46435775/ebaaad1d-27d1-4cf4-a106-7575623f9d73">
<img width="191" alt="3" src="https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/46435775/2ce616e5-f147-471a-86b6-218723db647c">

**Comment by shi-an** [comment]
但是我是右键 右键菜单的空白部分

**Comment by shi-an** [comment]
编辑消息内容变成编辑右键菜单内容

**Comment by mimocvb** [comment]
懂了(⊙﹏⊙)

**Comment by mimocvb** [comment]
已更新
