### ISSUE TITLE
最后一个消息右键不会显示修改消息内容

### ISSUE THREAD

**Issue by shi-an** [mimocvb/LiteLoaderQQNT-MessageEdit#3]
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/6a575f07-2690-4138-a612-754f6d8c07a5)
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/4aa493f0-5901-4ff2-a898-77307b76c142)
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/af2aa04f-d4ff-4cca-b274-c4c4ba716d45)

顺便画个图标跟上方统一呗

**Comment by mimocvb** [comment]
问题已优化，稍后更新即可
