### ISSUE TITLE
重复右键菜单会显示多个修改消息内容

### ISSUE THREAD

**Issue by shi-an** [mimocvb/LiteLoaderQQNT-MessageEdit#7]
![image](https://github.com/mimocvb/LiteLoaderQQNT-MessageEdit/assets/79352488/d3b9911f-c756-4329-ba52-8ced89e40ab7)

**Comment by mimocvb** [comment]
我这边复现不了，说下如何操作的，我这边尝试重复右键没有出现多个按钮

**Comment by shi-an** [comment]
右键 右键菜单的空白部分

**Comment by shi-an** [comment]
大佬群里哪个啊

**Comment by mimocvb** [comment]
问题已优化，稍后更新即可
